MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeads"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
#==================================蒸馏参数=====================================
DISTILL:
  DO: True
  PATH_T: 'detectron2/save/resnet56_vanilla/ckpt_epoch_240.pth'
  DISTILL: 'kd'
  # choices =  ['kd', 'hint', 'attention', 'similarity','correlation', 'vid', 'crd', 'kdsvd', 'fsp',
  #             'rkd', 'pkt', 'abound', 'factor', 'nst']
  # trial id
  TRIAL: 1.0
  # weight for classification
  R: 0.1    
  # weight balance for KD
  A: 0.9     
  # weight balance for other losses
  B: 0.0