DO: True
PATH_T: 'configs/Distillation.yaml'
DISTILL: 'kd'
# choices =  ['kd', 'hint', 'attention', 'similarity','correlation', 'vid', 'crd', 'kdsvd', 'fsp',
#             'rkd', 'pkt', 'abound', 'factor', 'nst']
# trial id
TRIAL: 1  
# weight for classification
R: 0.1    
# weight balance for KD
A: 0.9     
# weight balance for other losses
B: 0     
